### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by iblislin** [pi314/ascii-arts#2]
有沒有火星貓? :octocat:

**Comment by pi314** [comment]
有沒有參考圖？

**Comment by iblislin** [comment]
![這個](https://camo.githubusercontent.com/fc74cf4a092fe0d9d193bdc46b0f9821883fa3cd/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f37323931392f3338313630382f30373464306230362d613565332d313165322d386237662d3966303965623264646661652e6a7067)

**Comment by pi314** [comment]
原來是這隻，沒注意到 issue 名字XD
https://github.com/pi314/ascii-arts/blob/master/gallery/octocat.png
不過觸手上面的點點我畫不出來，太細了

**Comment by iblislin** [comment]
Wooow :+1:
